project:
  type: website
  output-dir: _output

website:
  title: "Contract Clause Analyzer"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/gu-dsan6725/spring-2026-final-project-team_05
        aria-label: GitHub

  page-footer:
    left: |
      DSAN 6725 — Spring 2026
    right: "Alison Manna, Akshay Arun, Satomi Ito"

format:
  html:
    theme: cosmo
    toc: false
